barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1020476, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1020476 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d6d56d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1014016, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1014016 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d6d5650>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1019668, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1019668 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d6d5610>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1025371, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1025371 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d6d5690>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1012832, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1012832 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d655950>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1020028, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1020028 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d5399d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1013978, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1013978 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d5398d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1022219, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1022219 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d6d5750>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta - WARNING - Kindergarten "Espira Oreid barnehage" https://nbr.udir.no/enhet/1026302, returned 404 at http://barnehagefakta.no/api/barnehage/1026302. The kindergarten is probably discontinued.
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1020143, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1020143 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d763850>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1020758, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1020758 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d763950>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1020220, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1020220 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d763990>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1021879, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1021879 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d763a10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1025561, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1025561 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d763a90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1013979, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1013979 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d763b10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1012834, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1012834 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d763b90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1022156, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1022156 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d763c10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1021749, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1021749 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d763c90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1020282, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1020282 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d763d10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1018458, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1018458 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d763d90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1017647, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1017647 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d763e10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1019506, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1019506 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d6d5710>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1016197, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1016197 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d6d5ad0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1021288, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1021288 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d6d5650>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1019670, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1019670 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d6d5610>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1020482, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1020482 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d655250>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1019669, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1019669 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d763950>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1021821, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1021821 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d763990>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1015051, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1015051 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d763a10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1025298, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1025298 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d763d10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1017093, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1017093 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d7637d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1021041, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1021041 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d763790>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1020597, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1020597 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d7638d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1012831, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1012831 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d763f90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1021127, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1021127 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d763c10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1022198, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1022198 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d655910>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1012833, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1012833 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d6ef0d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - ERROR - Could not connect to http://barnehagefakta.no/api/barnehage/1014018, try again later? HTTPConnectionPool(host='barnehagefakta.no', port=80): Max retries exceeded with url: /api/barnehage/1014018 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10d6ef150>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
barnehagefakta.get - WARNING - Change in response for id=1019678, archiving old result
barnehagefakta - WARNING - Kindergarten "Østerbo barnehage" https://nbr.udir.no/enhet/1019678, returned 404 at http://barnehagefakta.no/api/barnehage/1019678. The kindergarten is probably discontinued.
barnehagefakta.get - WARNING - Change in response for id=1020624, archiving old result
